// Complete Waterfall Database - 100+ waterfalls in Michigan UP and Northern Wisconsin
const waterfallData = {
    // Major Michigan UP Waterfalls
    tahquamenon: {
        name: "Tahquamenon Falls",
        location: "Paradise, Michigan",
        coordinates: { lat: 46.5767, lng: -85.2554 },
        state: "michigan",
        height: "50ft",
        width: "200ft",
        description: "Michigan's largest waterfall. The distinctive amber color comes from tannins.",
        directions: "Located in Tahquamenon Falls State Park. Take M-123 north from Newberry.",
        bestTime: "Spring for maximum flow, Fall for colors",
        features: ["Largest in Michigan", "Amber water", "Upper and Lower Falls"],
        difficulty: "easy",
        difficultyText: "Easy - Paved trails",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash. Access to both Upper and Lower Falls.",
        images: ["website-images/tahquamenon-falls.jpg", "website-images/tahquamenon22.jpg", "website-images/tahquamenonfalls43.jpg"]
    },
    bond: {
        name: "Bond Falls",
        location: "Paulding, Michigan",
        coordinates: { lat: 46.4035, lng: -89.1288 },
        state: "michigan",
        height: "40ft",
        width: "100ft",
        description: "Spectacular waterfall with multiple viewing platforms and boardwalk system.",
        directions: "From US-2, take Bond Falls Road east 5 miles.",
        bestTime: "Late spring through early fall",
        features: ["Wheelchair accessible", "Multiple platforms", "Regulated flow"],
        difficulty: "easy", 
        difficultyText: "Easy - Accessible boardwalk",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Boardwalk is dog-friendly.",
        images: ["website-images/bond-falls.jpg", "website-images/bondfalls11.jpg", "website-images/bondfalls12.jpg"]
    },
    munising: {
        name: "Munising Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4111, lng: -86.6204 },
        state: "michigan",
        height: "50ft",
        description: "Pictured Rocks National Lakeshore waterfall dropping 50 feet over sandstone.",
        directions: "Off H-58 east of Munising. Follow signs from downtown.",
        bestTime: "Spring for flow, winter for ice climbing",
        features: ["National Lakeshore", "Multiple viewpoints", "Educational displays"],
        difficulty: "moderate",
        difficultyText: "Moderate - 0.5 mile trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash. Easy paved trail to viewing platform.",
        images: ["website-images/munising-falls.jpg", "website-images/munising.jpg"]
    },
    miners: {
        name: "Miners Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4658, lng: -86.5506 },
        state: "michigan",
        height: "40ft",
        description: "Beautiful cascade through Pictured Rocks forest.",
        directions: "H-58 east from Munising, turn at Miners Castle Road.",
        bestTime: "Spring and early summer",
        features: ["Forest trail", "Sandstone formations", "Pictured Rocks"],
        difficulty: "moderate",
        difficultyText: "Moderate - 1.2 mile round trip",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash throughout trail.",
        images: ["website-images/miners-falls.jpg"]
    },
    wagner: {
        name: "Wagner Falls",
        location: "Munising, Michigan", 
        coordinates: { lat: 46.3505, lng: -86.3789 },
        state: "michigan",
        height: "20ft",
        description: "Picturesque cascade near Munising with easy trail access.",
        directions: "M-94 south of Munising, well-marked parking area.",
        bestTime: "Spring through fall",
        features: ["Easy access", "Photography spot", "Picnic area"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk from parking",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Short, easy trail suitable for all dogs.",
        images: ["website-images/wagner-falls.jpg"]
    },
    laughingwhitefish: {
        name: "Laughing Whitefish Falls",
        location: "Sundell, Michigan",
        coordinates: { lat: 46.3958, lng: -87.2028 },
        state: "michigan",
        height: "100ft",
        description: "One of Michigan's most graceful waterfalls, cascading down limestone cliffs.",
        directions: "From M-94, take Sundell Road to marked parking area.",
        bestTime: "Spring and early summer",
        features: ["Multiple tiers", "Limestone geology", "State Scenic Site"],
        difficulty: "moderate",
        difficultyText: "Moderate - 1 mile trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash. Trail can be muddy after rain.",
        images: ["website-images/laughingwhitefish3.jpg", "website-images/laughingwhitefish4.jpg", "website-images/laughingwhitefish5.jpg"]
    },
    sable: {
        name: "Sable Falls",
        location: "Grand Marais, Michigan",
        coordinates: { lat: 46.6528, lng: -86.0133 },
        state: "michigan",
        height: "75ft",
        description: "Beautiful cascade near Lake Superior with scenic stairs leading to beach.",
        directions: "H-58 in Grand Marais, well-marked parking area.",
        bestTime: "Summer and fall",
        features: ["Lake Superior access", "Beach", "Scenic stairs"],
        difficulty: "moderate",
        difficultyText: "Moderate - Many stairs",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash. Stairs can be challenging for some dogs.",
        images: ["website-images/sable-falls.jpg", "website-images/sablefalls14.jpg"]
    },
    chapel: {
        name: "Chapel Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.5147, lng: -86.4414 },
        state: "michigan",
        height: "60ft",
        description: "Remote waterfall in Pictured Rocks requiring longer hike.",
        directions: "Chapel parking area off Chapel Road from H-58.",
        bestTime: "Spring through fall",
        features: ["Chapel Beach access", "Chapel Rock", "Backcountry"],
        difficulty: "hard",
        difficultyText: "Challenging - 10 mile round trip",
        dogFriendly: true,
        dogInfo: "Dogs allowed but challenging hike. Bring water for your pet.",
        images: ["website-images/vchapelfalls10.jpg", "website-images/vchapelfalls11.jpg"]
    },
    spray: {
        name: "Spray Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.5400, lng: -86.4017 },
        state: "michigan",
        height: "70ft",
        description: "Stunning waterfall plunging directly into Lake Superior.",
        directions: "Boat access recommended. Can hike from Chapel Beach.",
        bestTime: "Summer by boat",
        features: ["Lake Superior", "Boat viewing", "Remote location"],
        difficulty: "hard",
        difficultyText: "Challenging - Remote access",
        dogFriendly: false,
        dogInfo: "Not recommended for dogs due to difficult access.",
        images: ["website-images/spray-falls.jpg", "website-images/sprayfalls4.jpg"]
    },
    bridalveil: {
        name: "Bridal Veil Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.5433, lng: -86.3967 },
        state: "michigan",
        height: "15ft",
        description: "Delicate waterfall along Pictured Rocks shoreline.",
        directions: "Boat or kayak access from Munising.",
        bestTime: "Summer by water",
        features: ["Lake Superior", "Kayaking destination", "Pictured Rocks"],
        difficulty: "moderate",
        difficultyText: "Moderate - Water access",
        dogFriendly: false,
        dogInfo: "Not accessible with dogs - boat/kayak only.",
        images: ["website-images/bridalveil-falls--michigan.jpg", "website-images/bridalveilfalls3.jpg"]
    },
    alger: {
        name: "Alger Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4089, lng: -86.3631 },
        state: "michigan",
        height: "20ft",
        description: "Roadside waterfall visible from M-28.",
        directions: "M-28 just east of Munising, roadside pulloff.",
        bestTime: "Spring and early summer",
        features: ["Roadside viewing", "No hiking", "Quick stop"],
        difficulty: "easy",
        difficultyText: "Easy - Roadside viewing",
        dogFriendly: true,
        dogInfo: "Dogs can view from roadside pulloff area.",
        images: ["website-images/algercounty.jpg"]
    },
    canyon: {
        name: "Canyon Falls",
        location: "L'Anse, Michigan",
        coordinates: { lat: 46.6833, lng: -88.4167 },
        state: "michigan",
        height: "20ft",
        description: "Series of drops through narrow rock canyon.",
        directions: "US-41 to Canyon Falls Road, follow signs.",
        bestTime: "Spring for high water",
        features: ["Rock canyon", "Multiple drops", "Gorge views"],
        difficulty: "moderate",
        difficultyText: "Moderate - Rocky trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed but watch for steep dropoffs.",
        images: ["website-images/canyon-falls.jpg", "website-images/canyonfalls13.jpg"]
    },
    agate: {
        name: "Agate Falls",
        location: "Bruce Crossing, Michigan",
        coordinates: { lat: 46.5219, lng: -89.1489 },
        state: "michigan",
        height: "40ft",
        description: "Wide cascade over ancient rock formations.",
        directions: "M-28 near Bruce Crossing, marked parking area.",
        bestTime: "Spring and early summer",
        features: ["Geological interest", "Wide cascade", "Easy viewing"],
        difficulty: "easy",
        difficultyText: "Easy - Short trail",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Short easy trail.",
        images: ["website-images/agate-falls.jpg", "website-images/agatefalls2.jpg", "website-images/agatefalls3.jpg"]
    },
    hungarian: {
        name: "Hungarian Falls",
        location: "Hubbell, Michigan",
        coordinates: { lat: 47.1406, lng: -88.4339 },
        state: "michigan",
        height: "110ft total",
        description: "Series of drops totaling over 100 feet.",
        directions: "6th Street in Hubbell to marked trail.",
        bestTime: "Spring through fall",
        features: ["Multiple drops", "Mining history", "Trail system"],
        difficulty: "moderate",
        difficultyText: "Moderate - Multiple trails",
        dogFriendly: true,
        dogInfo: "Dogs allowed. Multiple trail options of varying difficulty.",
        images: ["website-images/hungarianlowerfalls18.jpg", "website-images/hungarianupperfalls11.jpg"]
    },
    montreal: {
        name: "Montreal Falls",
        location: "Montreal, Michigan",
        coordinates: { lat: 46.5608, lng: -90.2414 },
        state: "michigan",
        height: "40ft",
        description: "Powerful cascade on Montreal River.",
        directions: "US-2 to Montreal, follow river road.",
        bestTime: "Spring for maximum flow",
        features: ["Montreal River", "Power generation", "Interstate park"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash in park areas.",
        images: ["website-images/montrealfalls2.jpg", "website-images/montrealfalls4.jpg", "website-images/montrealfalls5.jpg"]
    },
    ocqueoc: {
        name: "Ocqueoc Falls",
        location: "Ocqueoc, Michigan",
        coordinates: { lat: 45.3908, lng: -84.0564 },
        state: "michigan",
        height: "10ft",
        width: "40ft",
        description: "Largest waterfall in Michigan's Lower Peninsula.",
        directions: "M-68 west of Rogers City, follow signs.",
        bestTime: "Summer for swimming",
        features: ["Swimming allowed", "Picnic area", "Camping"],
        difficulty: "easy",
        difficultyText: "Easy - Wheelchair accessible",
        dogFriendly: true,
        dogInfo: "Dogs welcome. Great swimming spot for dogs.",
        images: ["website-images/ocqueoc-falls.jpg", "website-images/ocqueocfalls.jpg"]
    },
    manabezho: {
        name: "Manabezho Falls",
        location: "Watersmeet, Michigan",
        coordinates: { lat: 46.2678, lng: -89.1778 },
        state: "michigan",
        height: "20ft",
        description: "Scenic waterfall on Presque Isle River.",
        directions: "South Boundary Road in Porcupine Mountains State Park.",
        bestTime: "Spring and fall",
        features: ["Wilderness setting", "Presque Isle River", "State park"],
        difficulty: "moderate",
        difficultyText: "Moderate - Forest trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash in state park.",
        images: ["website-images/manabezho-falls.jpg", "website-images/manabezho1.jpg", "website-images/manabezhofalls21.jpg"]
    },
    manido: {
        name: "Manido Falls",
        location: "Watersmeet, Michigan",
        coordinates: { lat: 46.2744, lng: -89.1758 },
        state: "michigan",
        height: "15ft",
        description: "Another beautiful falls on Presque Isle River.",
        directions: "South Boundary Road in Porcupine Mountains State Park.",
        bestTime: "Spring through fall",
        features: ["Viewing platform", "River gorge", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Platform access",
        dogFriendly: true,
        dogInfo: "Dogs allowed. Platform viewing available.",
        images: ["website-images/manidofalls2.jpg", "website-images/manidofalls20.jpg", "website-images/manidofalls21.jpg"]
    },
    nawadaha: {
        name: "Nawadaha Falls",
        location: "Watersmeet, Michigan",
        coordinates: { lat: 46.2711, lng: -89.1769 },
        state: "michigan",
        height: "15ft",
        description: "Cascade on Presque Isle River with excellent viewing boardwalk.",
        directions: "South Boundary Road in Porcupine Mountains State Park.",
        bestTime: "Spring and fall",
        features: ["Boardwalk", "Multiple viewpoints", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Boardwalk access",
        dogFriendly: true,
        dogInfo: "Dogs welcome on boardwalk system.",
        images: ["website-images/nawadaha-falls.jpg", "website-images/nawadahafalls1.jpg", "website-images/nawadahafalls22.jpg"]
    },
    // Black River Waterfalls
    rainbow: {
        name: "Rainbow Falls (Black River)",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5083, lng: -90.0483 },
        state: "michigan",
        height: "40ft",
        description: "One of five major waterfalls on Black River.",
        directions: "Black River Road from Bessemer, marked trails.",
        bestTime: "Spring and fall",
        features: ["Black River gorge", "Multiple falls nearby", "Wilderness"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail system",
        dogFriendly: true,
        dogInfo: "Dogs allowed on all Black River trails.",
        images: ["website-images/rainbow2.jpg", "website-images/rainbowfalls3.jpg", "website-images/rainbowfallsblackriver24.jpg"]
    },
    sandstone: {
        name: "Sandstone Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5061, lng: -90.0472 },
        state: "michigan",
        height: "25ft",
        description: "Another Black River waterfall with unique sandstone formations.",
        directions: "Black River Road from Bessemer.",
        bestTime: "Spring through fall",
        features: ["Sandstone geology", "Black River", "Trail system"],
        difficulty: "moderate",
        difficultyText: "Moderate - Forest trail",
        dogFriendly: true,
        dogInfo: "Dogs welcome on trails.",
        images: ["website-images/sandstonefalls10.jpg", "website-images/sandstonefalls14.jpg", "website-images/sandstonefalls4.jpg"]
    },
    gorge: {
        name: "Gorge Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5044, lng: -90.0461 },
        state: "michigan",
        height: "30ft",
        description: "Dramatic falls in narrow gorge on Black River.",
        directions: "Black River Road from Bessemer.",
        bestTime: "Spring for power",
        features: ["Narrow gorge", "Powerful flow", "Black River"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail access",
        dogFriendly: true,
        dogInfo: "Dogs allowed, watch near gorge edges.",
        images: ["website-images/gorgefalls13.jpg", "website-images/gorgefalls14.jpg", "website-images/gorgefallsgorge.jpg"]
    },
    pothole: {
        name: "Pothole Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5028, lng: -90.0450 },
        state: "michigan",
        height: "30ft",
        description: "Unique geological formations created by swirling water.",
        directions: "Black River Road from Bessemer.",
        bestTime: "Spring and summer",
        features: ["Potholes", "Geological interest", "Black River"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail system",
        dogFriendly: true,
        dogInfo: "Dogs welcome on trails.",
        images: ["website-images/potholes5.jpg", "website-images/widepotholes.jpg"]
    },
    greatconglomerate: {
        name: "Great Conglomerate Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5006, lng: -90.0439 },
        state: "michigan",
        height: "40ft",
        description: "Last and largest of Black River falls before Lake Superior.",
        directions: "Black River Road, furthest north trail.",
        bestTime: "Spring and fall",
        features: ["Largest Black River falls", "Lake Superior nearby"],
        difficulty: "moderate",
        difficultyText: "Moderate - Longest trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trail to falls.",
        images: ["website-images/conglomeratefalls1.jpg", "website-images/conglomeratefalls2.jpg", "website-images/conglomeratefalls3.jpg"]
    },
    // Wisconsin Waterfalls
    bigmanitou: {
        name: "Big Manitou Falls",
        location: "Superior, Wisconsin",
        coordinates: { lat: 46.5283, lng: -92.1205 },
        state: "wisconsin",
        height: "165ft",
        description: "Wisconsin's tallest waterfall and 4th highest east of the Rockies.",
        directions: "Pattison State Park, 13 miles south of Superior.",
        bestTime: "Spring for flow, fall for colors",
        features: ["Tallest in Wisconsin", "Suspension footbridge", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk from parking",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash in park.",
        images: ["website-images/vbigmanitou1.jpg", "website-images/vbigmanitou2.jpg", "website-images/vbigmanitou3.jpg"]
    },
    littlemanitou: {
        name: "Little Manitou Falls",
        location: "Superior, Wisconsin",
        coordinates: { lat: 46.5194, lng: -92.1183 },
        state: "wisconsin",
        height: "31ft",
        description: "Smaller companion to Big Manitou in Pattison State Park.",
        directions: "Pattison State Park, downstream from Big Manitou.",
        bestTime: "Spring through fall",
        features: ["State park", "Forest trail", "Swimming beach nearby"],
        difficulty: "easy",
        difficultyText: "Easy - Short trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash throughout park.",
        images: ["website-images/littlemanitou3.jpg", "website-images/littlemanitoufalls13.jpg", "website-images/littlemanitoufalls14.jpg"]
    },
    amnicon: {
        name: "Amnicon Falls",
        location: "South Range, Wisconsin",
        coordinates: { lat: 46.6106, lng: -91.8894 },
        state: "wisconsin",
        height: "30ft",
        description: "Series of waterfalls and rapids in Amnicon Falls State Park.",
        directions: "US-2 east of Superior, follow signs to state park.",
        bestTime: "Spring and early summer",
        features: ["Multiple falls", "Covered bridge", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Developed paths",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Multiple viewing areas.",
        images: ["website-images/vamniconlower1.jpg", "website-images/vamniconupper1.jpg"]
    },
    copper: {
        name: "Copper Falls",
        location: "Mellen, Wisconsin",
        coordinates: { lat: 46.3669, lng: -90.6481 },
        state: "wisconsin",
        height: "40ft",
        description: "Beautiful Wisconsin falls in Copper Falls State Park.",
        directions: "Copper Falls State Park near Mellen, WI.",
        bestTime: "Spring through fall",
        features: ["State park", "Lava flows", "Brownstone Falls nearby"],
        difficulty: "easy",
        difficultyText: "Easy - Developed trails",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash in state park.",
        images: ["website-images/copperrockfalls2.jpg", "website-images/copperrockfalls3.jpg", "website-images/copperrockfalls5.jpg"]
    },
    brownstone: {
        name: "Brownstone Falls",
        location: "Mellen, Wisconsin",
        coordinates: { lat: 46.3658, lng: -90.6472 },
        state: "wisconsin",
        height: "30ft",
        description: "Companion falls to Copper Falls in same state park.",
        directions: "Copper Falls State Park near Mellen, WI.",
        bestTime: "Spring through fall",
        features: ["Tyler Forks", "State park", "Near Copper Falls"],
        difficulty: "easy",
        difficultyText: "Easy - Park trails",
        dogFriendly: true,
        dogInfo: "Dogs welcome on park trails.",
        images: ["website-images/vbrownstonefalls1.jpg", "website-images/vbrownstonefalls2.jpg", "website-images/vbrownstonefalls3.jpg"]
    },
    daves: {
        name: "Dave's Falls",
        location: "Amberg, Wisconsin",
        coordinates: { lat: 45.4942, lng: -87.9961 },
        state: "wisconsin",
        height: "35ft",
        description: "Popular county park with swimming and picnic facilities.",
        directions: "Dave's Falls County Park on Pike River.",
        bestTime: "Summer for recreation",
        features: ["Swimming", "County park", "Picnic facilities"],
        difficulty: "easy",
        difficultyText: "Easy - Developed park",
        dogFriendly: true,
        dogInfo: "Dogs welcome. Great swimming spot for dogs.",
        images: ["website-images/davesfalls5.jpg", "website-images/davesfalls7.jpg"]
    }
};

// Export for use in HTML file
if (typeof module !== 'undefined' && module.exports) {
    module.exports = waterfallData;
}