// Complete Waterfall Database - 350+ waterfalls in Michigan UP and Northern Wisconsin
const waterfallData = {
    // Major Michigan UP Waterfalls
    tahquamenon: {
        name: "Tahquamenon Falls",
        location: "Paradise, Michigan",
        coordinates: { lat: 46.5767, lng: -85.2554 },
        state: "michigan",
        height: "50ft",
        width: "200ft",
        description: "Michigan's largest waterfall. The distinctive amber color comes from tannins.",
        directions: "Located in Tahquamenon Falls State Park. Take M-123 north from Newberry.",
        bestTime: "Spring for maximum flow, Fall for colors",
        features: ["Largest in Michigan", "Amber water", "Upper and Lower Falls"],
        difficulty: "easy",
        difficultyText: "Easy - Paved trails",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash. Access to both Upper and Lower Falls.",
        images: ["website-images/tahquamenon-falls.jpg", "website-images/tahquamenon22.jpg"]
    },
    bond: {
        name: "Bond Falls",
        location: "Paulding, Michigan",
        coordinates: { lat: 46.4035, lng: -89.1288 },
        state: "michigan",
        height: "40ft",
        width: "100ft",
        description: "Spectacular waterfall with multiple viewing platforms and boardwalk system.",
        directions: "From US-2, take Bond Falls Road east 5 miles.",
        bestTime: "Late spring through early fall",
        features: ["Wheelchair accessible", "Multiple platforms", "Regulated flow"],
        difficulty: "easy",
        difficultyText: "Easy - Accessible boardwalk",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Boardwalk is dog-friendly.",
        images: ["bond-falls.jpg", "bondfalls12.jpg"]
    },
    munising: {
        name: "Munising Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4111, lng: -86.6204 },
        state: "michigan",
        height: "50ft",
        description: "Pictured Rocks National Lakeshore waterfall dropping 50 feet over sandstone.",
        directions: "Off H-58 east of Munising. Follow signs from downtown.",
        bestTime: "Spring for flow, winter for ice climbing",
        features: ["National Lakeshore", "Multiple viewpoints", "Educational displays"],
        difficulty: "moderate",
        difficultyText: "Moderate - 0.5 mile trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash. Easy paved trail to viewing platform.",
        images: ["munising-falls.jpg"]
    },
    miners: {
        name: "Miners Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4658, lng: -86.5506 },
        state: "michigan",
        height: "40ft",
        description: "Beautiful cascade through Pictured Rocks forest.",
        directions: "H-58 east from Munising, turn at Miners Castle Road.",
        bestTime: "Spring and early summer",
        features: ["Forest trail", "Sandstone formations", "Pictured Rocks"],
        difficulty: "moderate",
        difficultyText: "Moderate - 1.2 mile round trip",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash throughout trail.",
        images: ["miners-falls.jpg"]
    },
    wagner: {
        name: "Wagner Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.3505, lng: -86.3789 },
        state: "michigan",
        height: "20ft",
        description: "Picturesque cascade near Munising with easy trail access.",
        directions: "M-94 south of Munising, well-marked parking area.",
        bestTime: "Spring through fall",
        features: ["Easy access", "Photography spot", "Picnic area"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk from parking",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Short, easy trail suitable for all dogs.",
        images: ["wagner-falls.jpg"]
    },
    laughingwhitefish: {
        name: "Laughing Whitefish Falls",
        location: "Sundell, Michigan",
        coordinates: { lat: 46.3958, lng: -87.2028 },
        state: "michigan",
        height: "100ft",
        description: "One of Michigan's most graceful waterfalls, cascading down limestone cliffs.",
        directions: "From M-94, take Sundell Road to marked parking area.",
        bestTime: "Spring and early summer",
        features: ["Multiple tiers", "Limestone geology", "State Scenic Site"],
        difficulty: "moderate",
        difficultyText: "Moderate - 1 mile trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash. Trail can be muddy after rain.",
        images: ["laughingwhitefish3.jpg"]
    },
    sable: {
        name: "Sable Falls",
        location: "Grand Marais, Michigan",
        coordinates: { lat: 46.6528, lng: -86.0133 },
        state: "michigan",
        height: "75ft",
        description: "Beautiful cascade near Lake Superior with scenic stairs leading to beach.",
        directions: "H-58 in Grand Marais, well-marked parking area.",
        bestTime: "Summer and fall",
        features: ["Lake Superior access", "Beach", "Scenic stairs"],
        difficulty: "moderate",
        difficultyText: "Moderate - Many stairs",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash. Stairs can be challenging for some dogs.",
        images: ["sable-falls.jpg"]
    },
    chapel: {
        name: "Chapel Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.5147, lng: -86.4414 },
        state: "michigan",
        height: "60ft",
        description: "Remote waterfall in Pictured Rocks requiring longer hike.",
        directions: "Chapel parking area off Chapel Road from H-58.",
        bestTime: "Spring through fall",
        features: ["Chapel Beach access", "Chapel Rock", "Backcountry"],
        difficulty: "hard",
        difficultyText: "Challenging - 10 mile round trip",
        dogFriendly: true,
        dogInfo: "Dogs allowed but challenging hike. Bring water for your pet.",
        images: ["vchapelfalls10.jpg"]
    },
    spray: {
        name: "Spray Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.5400, lng: -86.4017 },
        state: "michigan",
        height: "70ft",
        description: "Stunning waterfall plunging directly into Lake Superior.",
        directions: "Boat access recommended. Can hike from Chapel Beach.",
        bestTime: "Summer by boat",
        features: ["Lake Superior", "Boat viewing", "Remote location"],
        difficulty: "hard",
        difficultyText: "Challenging - Remote access",
        dogFriendly: false,
        dogInfo: "Not recommended for dogs due to difficult access.",
        images: ["spray-falls.jpg"]
    },
    bridalveil: {
        name: "Bridal Veil Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.5433, lng: -86.3967 },
        state: "michigan",
        height: "15ft",
        description: "Delicate waterfall along Pictured Rocks shoreline.",
        directions: "Boat or kayak access from Munising.",
        bestTime: "Summer by water",
        features: ["Lake Superior", "Kayaking destination", "Pictured Rocks"],
        difficulty: "moderate",
        difficultyText: "Moderate - Water access",
        dogFriendly: false,
        dogInfo: "Not accessible with dogs - boat/kayak only.",
        images: ["bridalveil-falls--michigan.jpg"]
    },
    alger: {
        name: "Alger Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4089, lng: -86.3631 },
        state: "michigan",
        height: "20ft",
        description: "Roadside waterfall visible from M-28.",
        directions: "M-28 just east of Munising, roadside pulloff.",
        bestTime: "Spring and early summer",
        features: ["Roadside viewing", "No hiking", "Quick stop"],
        difficulty: "easy",
        difficultyText: "Easy - Roadside viewing",
        dogFriendly: true,
        dogInfo: "Dogs can view from roadside pulloff area.",
        images: ["algercounty.jpg"]
    },
    canyon: {
        name: "Canyon Falls",
        location: "L'Anse, Michigan",
        coordinates: { lat: 46.6833, lng: -88.4167 },
        state: "michigan",
        height: "20ft",
        description: "Series of drops through narrow rock canyon.",
        directions: "US-41 to Canyon Falls Road, follow signs.",
        bestTime: "Spring for high water",
        features: ["Rock canyon", "Multiple drops", "Gorge views"],
        difficulty: "moderate",
        difficultyText: "Moderate - Rocky trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed but watch for steep dropoffs.",
        images: ["canyon-falls.jpg"]
    },
    agate: {
        name: "Agate Falls",
        location: "Bruce Crossing, Michigan",
        coordinates: { lat: 46.5219, lng: -89.1489 },
        state: "michigan",
        height: "40ft",
        description: "Wide cascade over ancient rock formations.",
        directions: "M-28 near Bruce Crossing, marked parking area.",
        bestTime: "Spring and early summer",
        features: ["Geological interest", "Wide cascade", "Easy viewing"],
        difficulty: "easy",
        difficultyText: "Easy - Short trail",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Short easy trail.",
        images: ["agate-falls.jpg"]
    },
    hungarian: {
        name: "Hungarian Falls",
        location: "Hubbell, Michigan",
        coordinates: { lat: 47.1406, lng: -88.4339 },
        state: "michigan",
        height: "110ft total",
        description: "Series of drops totaling over 100 feet.",
        directions: "6th Street in Hubbell to marked trail.",
        bestTime: "Spring through fall",
        features: ["Multiple drops", "Mining history", "Trail system"],
        difficulty: "moderate",
        difficultyText: "Moderate - Multiple trails",
        dogFriendly: true,
        dogInfo: "Dogs allowed. Multiple trail options of varying difficulty.",
        images: ["hungarianlowerfalls18.jpg"]
    },
    montreal: {
        name: "Montreal Falls",
        location: "Montreal, Michigan",
        coordinates: { lat: 46.5608, lng: -90.2414 },
        state: "michigan",
        height: "40ft",
        description: "Powerful cascade on Montreal River.",
        directions: "US-2 to Montreal, follow river road.",
        bestTime: "Spring for maximum flow",
        features: ["Montreal River", "Power generation", "Interstate park"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash in park areas.",
        images: ["montrealfalls2.jpg"]
    },
    ocqueoc: {
        name: "Ocqueoc Falls",
        location: "Ocqueoc, Michigan",
        coordinates: { lat: 45.3908, lng: -84.0564 },
        state: "michigan",
        height: "10ft",
        width: "40ft",
        description: "Largest waterfall in Michigan's Lower Peninsula.",
        directions: "M-68 west of Rogers City, follow signs.",
        bestTime: "Summer for swimming",
        features: ["Swimming allowed", "Picnic area", "Camping"],
        difficulty: "easy",
        difficultyText: "Easy - Wheelchair accessible",
        dogFriendly: true,
        dogInfo: "Dogs welcome. Great swimming spot for dogs.",
        images: ["ocqueoc-falls.jpg"]
    },
    manabezho: {
        name: "Manabezho Falls",
        location: "Watersmeet, Michigan",
        coordinates: { lat: 46.2678, lng: -89.1778 },
        state: "michigan",
        height: "20ft",
        description: "Scenic waterfall on Presque Isle River.",
        directions: "South Boundary Road in Porcupine Mountains State Park.",
        bestTime: "Spring and fall",
        features: ["Wilderness setting", "Presque Isle River", "State park"],
        difficulty: "moderate",
        difficultyText: "Moderate - Forest trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash in state park.",
        images: ["manabezho-falls.jpg"]
    },
    manido: {
        name: "Manido Falls",
        location: "Watersmeet, Michigan",
        coordinates: { lat: 46.2744, lng: -89.1758 },
        state: "michigan",
        height: "15ft",
        description: "Another beautiful falls on Presque Isle River.",
        directions: "South Boundary Road in Porcupine Mountains State Park.",
        bestTime: "Spring through fall",
        features: ["Viewing platform", "River gorge", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Platform access",
        dogFriendly: true,
        dogInfo: "Dogs allowed. Platform viewing available.",
        images: ["manidofalls2.jpg"]
    },
    nawadaha: {
        name: "Nawadaha Falls",
        location: "Watersmeet, Michigan",
        coordinates: { lat: 46.2711, lng: -89.1769 },
        state: "michigan",
        height: "15ft",
        description: "Cascade on Presque Isle River with excellent viewing boardwalk.",
        directions: "South Boundary Road in Porcupine Mountains State Park.",
        bestTime: "Spring and fall",
        features: ["Boardwalk", "Multiple viewpoints", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Boardwalk access",
        dogFriendly: true,
        dogInfo: "Dogs welcome on boardwalk system.",
        images: ["nawadaha-falls.jpg"]
    },
    // Black River Waterfalls
    rainbow: {
        name: "Rainbow Falls (Black River)",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5083, lng: -90.0483 },
        state: "michigan",
        height: "40ft",
        description: "One of five major waterfalls on Black River.",
        directions: "Black River Road from Bessemer, marked trails.",
        bestTime: "Spring and fall",
        features: ["Black River gorge", "Multiple falls nearby", "Wilderness"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail system",
        dogFriendly: true,
        dogInfo: "Dogs allowed on all Black River trails.",
        images: ["rainbowfallsblackriver24.jpg"]
    },
    sandstone: {
        name: "Sandstone Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5061, lng: -90.0472 },
        state: "michigan",
        height: "25ft",
        description: "Another Black River waterfall with unique sandstone formations.",
        directions: "Black River Road from Bessemer.",
        bestTime: "Spring through fall",
        features: ["Sandstone geology", "Black River", "Trail system"],
        difficulty: "moderate",
        difficultyText: "Moderate - Forest trail",
        dogFriendly: true,
        dogInfo: "Dogs welcome on trails.",
        images: ["sandstonefalls10.jpg"]
    },
    gorge: {
        name: "Gorge Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5044, lng: -90.0461 },
        state: "michigan",
        height: "30ft",
        description: "Dramatic falls in narrow gorge on Black River.",
        directions: "Black River Road from Bessemer.",
        bestTime: "Spring for power",
        features: ["Narrow gorge", "Powerful flow", "Black River"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail access",
        dogFriendly: true,
        dogInfo: "Dogs allowed, watch near gorge edges.",
        images: ["gorgefalls13.jpg"]
    },
    pothole: {
        name: "Pothole Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5028, lng: -90.0450 },
        state: "michigan",
        height: "30ft",
        description: "Unique geological formations created by swirling water.",
        directions: "Black River Road from Bessemer.",
        bestTime: "Spring and summer",
        features: ["Potholes", "Geological interest", "Black River"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail system",
        dogFriendly: true,
        dogInfo: "Dogs welcome on trails.",
        images: ["potholes5.jpg"]
    },
    greatconglomerate: {
        name: "Great Conglomerate Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5006, lng: -90.0439 },
        state: "michigan",
        height: "40ft",
        description: "Last and largest of Black River falls before Lake Superior.",
        directions: "Black River Road, furthest north trail.",
        bestTime: "Spring and fall",
        features: ["Largest Black River falls", "Lake Superior nearby"],
        difficulty: "moderate",
        difficultyText: "Moderate - Longest trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trail to falls.",
        images: ["conglomeratefalls1.jpg"]
    },
    // Keweenaw Peninsula Falls
    eagle: {
        name: "Eagle River Falls",
        location: "Eagle River, Michigan",
        coordinates: { lat: 47.4111, lng: -88.2944 },
        state: "michigan",
        height: "45ft",
        description: "Beautiful falls right in Eagle River village.",
        directions: "M-26 in Eagle River, park near bridge.",
        bestTime: "Spring through fall",
        features: ["In town", "Historic bridge", "Easy access"],
        difficulty: "easy",
        difficultyText: "Easy - In town location",
        dogFriendly: true,
        dogInfo: "Dogs welcome, village setting.",
        images: ["eagleriverfalls31.jpg"]
    },
    jacob: {
        name: "Jacobs Falls",
        location: "Eagle River, Michigan",
        coordinates: { lat: 47.4133, lng: -88.2956 },
        state: "michigan",
        height: "25ft",
        description: "Pretty cascade near Eagle River.",
        directions: "M-26 near Eagle River, local road access.",
        bestTime: "Spring through fall",
        features: ["Less crowded", "Forest setting", "Eagle River area"],
        difficulty: "moderate",
        difficultyText: "Moderate - Short hike",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trail.",
        images: ["vjacobfalls.jpg"]
    },
    manganese: {
        name: "Manganese Falls",
        location: "Copper Harbor, Michigan",
        coordinates: { lat: 47.4689, lng: -87.8856 },
        state: "michigan",
        height: "45ft",
        description: "Dramatic gorge waterfall near Copper Harbor.",
        directions: "Manganese Road from US-41 near Copper Harbor.",
        bestTime: "Spring through fall",
        features: ["Gorge setting", "Mining history", "Trail system"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail with stairs",
        dogFriendly: true,
        dogInfo: "Dogs allowed but steep sections.",
        images: ["manganesefalls2.jpg"]
    },
    montreal2: {
        name: "Montreal Falls (Michigan Side)",
        location: "Ironwood, Michigan",
        coordinates: { lat: 46.5000, lng: -90.1667 },
        state: "michigan",
        height: "40ft",
        description: "Michigan side viewing of Montreal River falls.",
        directions: "US-2 west of Ironwood.",
        bestTime: "Spring for high flow",
        features: ["Montreal River", "Interstate falls", "Power generation"],
        difficulty: "easy",
        difficultyText: "Easy - Viewing area",
        dogFriendly: true,
        dogInfo: "Dogs allowed in viewing areas.",
        images: ["montrealfalls5.jpg"]
    },
    sturgeon: {
        name: "Sturgeon Falls",
        location: "Sidnaw, Michigan",
        coordinates: { lat: 46.5939, lng: -88.5778 },
        state: "michigan",
        height: "25ft",
        description: "Remote waterfall on Sturgeon River.",
        directions: "FR-2200 from Sidnaw, rough road conditions.",
        bestTime: "Spring and early summer",
        features: ["Remote location", "Canyon", "Wilderness"],
        difficulty: "hard",
        difficultyText: "Challenging - Rough road access",
        dogFriendly: true,
        dogInfo: "Dogs allowed but rough access road.",
        images: ["sturgeonfalls2.jpg"]
    },
    douglashoughton: {
        name: "Douglass Houghton Falls",
        location: "Copper Harbor, Michigan",
        coordinates: { lat: 47.4269, lng: -87.8897 },
        state: "michigan",
        height: "110ft",
        description: "Michigan's tallest waterfall by total drop. Seasonal flow.",
        directions: "M-26 between Eagle River and Copper Harbor.",
        bestTime: "Spring snowmelt only",
        features: ["Tallest total drop", "Seasonal", "Roadside viewing"],
        difficulty: "easy",
        difficultyText: "Easy - Roadside viewing",
        dogFriendly: true,
        dogInfo: "Viewable from roadside with dogs.",
        images: ["houghtondells1.jpg"]
    },
    silverfalls: {
        name: "Silver River Falls",
        location: "Eagle Harbor, Michigan",
        coordinates: { lat: 47.4594, lng: -88.1578 },
        state: "michigan",
        height: "25ft",
        description: "Scenic falls near Eagle Harbor.",
        directions: "Silver River Road from Eagle Harbor.",
        bestTime: "Spring and early summer",
        features: ["Multiple drops", "Forest trail", "Eagle Harbor area"],
        difficulty: "moderate",
        difficultyText: "Moderate - Forest trail",
        dogFriendly: true,
        dogInfo: "Dogs welcome on forest trails.",
        images: ["silverriverfallskeewenaw22.jpg"]
    },
    // Additional UP Michigan Falls
    autrain: {
        name: "Au Train Falls",
        location: "Au Train, Michigan",
        coordinates: { lat: 46.4256, lng: -86.8394 },
        state: "michigan",
        height: "40ft",
        description: "Beautiful cascade with viewing platform.",
        directions: "H-03 south of Au Train.",
        bestTime: "Spring through fall",
        features: ["Viewing platform", "Historic site", "Easy access"],
        difficulty: "easy",
        difficultyText: "Easy - Platform viewing",
        dogFriendly: true,
        dogInfo: "Dogs allowed on viewing platform.",
        images: ["autrainfalls1.jpg"]
    },
    rock: {
        name: "Rock River Falls",
        location: "Chatham, Michigan",
        coordinates: { lat: 46.3472, lng: -86.9289 },
        state: "michigan",
        height: "20ft",
        description: "Series of cascades on Rock River.",
        directions: "Rock River Road from Chatham.",
        bestTime: "Summer for swimming",
        features: ["Swimming", "Multiple cascades", "Local favorite"],
        difficulty: "easy",
        difficultyText: "Easy - Short trails",
        dogFriendly: true,
        dogInfo: "Dogs love the swimming holes here.",
        images: ["rockriver5.jpg"]
    },
    scott: {
        name: "Scott Falls",
        location: "Au Train, Michigan",
        coordinates: { lat: 46.4033, lng: -86.8456 },
        state: "michigan",
        height: "10ft",
        description: "Roadside waterfall flowing under M-28.",
        directions: "M-28 west of Munising, roadside pulloff.",
        bestTime: "Spring and early summer",
        features: ["Roadside", "Quick stop", "Unique setting"],
        difficulty: "easy",
        difficultyText: "Easy - Roadside viewing",
        dogFriendly: true,
        dogInfo: "Quick roadside stop suitable for dogs.",
        images: ["scottcreekfalls.jpg"]
    },
    tannery: {
        name: "Tannery Falls",
        location: "Munising, Michigan",
        coordinates: { lat: 46.4097, lng: -86.6183 },
        state: "michigan",
        height: "40ft",
        description: "Urban waterfall in Munising with interesting industrial history.",
        directions: "Downtown Munising, behind old tannery site.",
        bestTime: "Spring through fall",
        features: ["Urban setting", "Historic", "Easy access"],
        difficulty: "easy",
        difficultyText: "Easy - Urban location",
        dogFriendly: true,
        dogInfo: "Dogs allowed, urban park setting.",
        images: ["tannerycreekfalls2.jpg"]
    },
    pinnacle: {
        name: "Pinnacle Falls",
        location: "Iron Mountain, Michigan",
        coordinates: { lat: 45.8236, lng: -88.0650 },
        state: "michigan",
        height: "40ft",
        description: "Hidden falls near Iron Mountain.",
        directions: "Pinnacle Falls Road from US-2.",
        bestTime: "Spring through fall",
        features: ["Rock climbing nearby", "Hidden gem", "Forest"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail required",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trails.",
        images: ["pinnaclefalls2.jpg"]
    },
    fumee: {
        name: "Fumee Falls",
        location: "Quinnesec, Michigan",
        coordinates: { lat: 45.8053, lng: -87.9956 },
        state: "michigan",
        height: "20ft",
        description: "Twin falls on Fumee Creek.",
        directions: "Fumee Lake Road near Quinnesec.",
        bestTime: "Spring and early summer",
        features: ["Twin falls", "Historic logging", "Fumee Creek"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail access",
        dogFriendly: true,
        dogInfo: "Dogs welcome on trail.",
        images: ["vfumeefalls11.jpg"]
    },
    piers: {
        name: "Piers Gorge",
        location: "Norway, Michigan",
        coordinates: { lat: 45.8078, lng: -88.0892 },
        state: "michigan",
        height: "30ft total",
        description: "Series of powerful rapids and falls.",
        directions: "Piers Gorge Road from US-8.",
        bestTime: "Spring for high water",
        features: ["Whitewater rafting", "Multiple drops", "Gorge"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail along gorge",
        dogFriendly: true,
        dogInfo: "Dogs allowed but keep away from rapids.",
        images: ["piersgorge1stpier1.jpg"]
    },
    victoria: {
        name: "Victoria Falls",
        location: "Rockland, Michigan",
        coordinates: { lat: 46.7344, lng: -89.1928 },
        state: "michigan",
        height: "40ft",
        description: "Remote waterfall requiring significant hike.",
        directions: "Victoria Dam Road from Rockland, long hike required.",
        bestTime: "Spring and summer",
        features: ["Remote", "Historic dam site", "Wilderness"],
        difficulty: "hard",
        difficultyText: "Challenging - 8 mile round trip",
        dogFriendly: true,
        dogInfo: "Dogs need good endurance for long hike.",
        images: ["victoriafalls.jpg"]
    },
    okundekun: {
        name: "O Kun de Kun Falls",
        location: "Bruce Crossing, Michigan",
        coordinates: { lat: 46.5272, lng: -89.1842 },
        state: "michigan",
        height: "30ft",
        description: "Beautiful cascade meaning 'water falling between rocks'.",
        directions: "Forest Road 323 from US-45.",
        bestTime: "Spring through fall",
        features: ["Native American name", "Forest setting", "Baltimore River"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail required",
        dogFriendly: true,
        dogInfo: "Dogs allowed on forest trails.",
        images: ["okundekunfalls13.jpg"]
    },
    gabbro: {
        name: "Gabbro Falls",
        location: "Bessemer, Michigan",
        coordinates: { lat: 46.5117, lng: -90.0500 },
        state: "michigan",
        height: "25ft",
        description: "Falls on Black River north of main falls.",
        directions: "Black River Road extension.",
        bestTime: "Spring through fall",
        features: ["Gabbro rock", "Black River", "Less visited"],
        difficulty: "moderate",
        difficultyText: "Moderate - Longer trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trail system.",
        images: ["gabbrofalls20.jpg"]
    },
    chicagon: {
        name: "Chicagon Falls",
        location: "Crystal Falls, Michigan",
        coordinates: { lat: 46.0983, lng: -88.3342 },
        state: "michigan",
        height: "30ft",
        description: "Falls on Paint River.",
        directions: "US-2 to Paint River Road.",
        bestTime: "Spring through fall",
        features: ["Paint River", "Fishing", "Forest"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail required",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trails.",
        images: ["chicagonfalls.jpg"]
    },
    haven: {
        name: "Haven Falls",
        location: "Lac La Belle, Michigan",
        coordinates: { lat: 47.3900, lng: -88.0289 },
        state: "michigan",
        height: "25ft",
        description: "Remote Keweenaw waterfall near Lac La Belle.",
        directions: "Haven Park Road from Lac La Belle.",
        bestTime: "Spring through fall",
        features: ["Remote", "Keweenaw", "Forest"],
        difficulty: "hard",
        difficultyText: "Challenging - Rough trail",
        dogFriendly: true,
        dogInfo: "Dogs need good trail experience.",
        images: ["havenfalls6.jpg"]
    },
    warner: {
        name: "Warner Falls",
        location: "Palmer, Michigan",
        coordinates: { lat: 46.4431, lng: -87.5933 },
        state: "michigan",
        height: "20ft",
        description: "Small falls near Palmer.",
        directions: "Warner Creek Road from Palmer.",
        bestTime: "Spring through fall",
        features: ["Picnic area", "Creek", "Family friendly"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk",
        dogFriendly: true,
        dogInfo: "Dogs welcome, family friendly area.",
        images: ["warnerfalls3.jpg"]
    },
    schweitzer: {
        name: "Schweitzer Falls",
        location: "Palmer, Michigan",
        coordinates: { lat: 46.4289, lng: -87.6222 },
        state: "michigan",
        height: "15ft",
        description: "Creek waterfall with swimming hole.",
        directions: "Schweitzer Creek Road from Palmer.",
        bestTime: "Summer for swimming",
        features: ["Swimming hole", "Creek", "Local spot"],
        difficulty: "easy",
        difficultyText: "Easy - Short trail",
        dogFriendly: true,
        dogInfo: "Great swimming spot for dogs.",
        images: ["vschweitzerfalls1.jpg"]
    },
    carp: {
        name: "Carp River Falls",
        location: "Marquette, Michigan",
        coordinates: { lat: 46.5547, lng: -87.4856 },
        state: "michigan",
        height: "15ft",
        description: "Falls on Carp River near Marquette.",
        directions: "County Road 553 north of Marquette.",
        bestTime: "Spring through fall",
        features: ["Carp River", "Near Marquette", "Multiple drops"],
        difficulty: "easy",
        difficultyText: "Easy - Near road",
        dogFriendly: true,
        dogInfo: "Dogs welcome, easy river access.",
        images: ["carpriverfalls2.jpg"]
    },
    dead: {
        name: "Dead River Falls",
        location: "Marquette, Michigan",
        coordinates: { lat: 46.6144, lng: -87.4753 },
        state: "michigan",
        height: "25ft",
        description: "Series of drops on Dead River.",
        directions: "County Road 510 north of Marquette.",
        bestTime: "Spring for high water",
        features: ["Dead River", "Multiple drops", "Hiking trails"],
        difficulty: "moderate",
        difficultyText: "Moderate - River trail",
        dogFriendly: true,
        dogInfo: "Dogs enjoy river trails here.",
        images: ["deadriver1drop.jpg"]
    },
    yellow: {
        name: "Yellow Dog Falls",
        location: "Big Bay, Michigan",
        coordinates: { lat: 46.7856, lng: -87.7286 },
        state: "michigan",
        height: "30ft",
        description: "Beautiful cascade on Yellow Dog River.",
        directions: "County Road 510 to Yellow Dog Plains Road.",
        bestTime: "Spring through fall",
        features: ["Yellow Dog River", "Wilderness", "Photography"],
        difficulty: "moderate",
        difficultyText: "Moderate - 2 mile trail",
        dogFriendly: true,
        dogInfo: "Despite the name, very dog-friendly trail!",
        images: ["yellowdogfalls1.jpg"]
    },
    littlegarlic: {
        name: "Little Garlic Falls",
        location: "Marquette, Michigan",
        coordinates: { lat: 46.6039, lng: -87.4578 },
        state: "michigan",
        height: "15ft",
        description: "Small falls on Little Garlic River.",
        directions: "Little Garlic Road north of Marquette.",
        bestTime: "Spring through fall",
        features: ["Little Garlic River", "Near Marquette", "Companion falls"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail required",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trail.",
        images: ["littlegarlicfalls.jpg"]
    },
    biggarlic: {
        name: "Big Garlic Falls",
        location: "Marquette, Michigan",
        coordinates: { lat: 46.6083, lng: -87.4544 },
        state: "michigan",
        height: "25ft",
        description: "Larger falls on Garlic River system.",
        directions: "Big Garlic Road north of Marquette.",
        bestTime: "Spring for best flow",
        features: ["Garlic River", "Local favorite", "Swimming"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail access",
        dogFriendly: true,
        dogInfo: "Dogs love swimming here in summer.",
        images: ["biggarlicfalls2.jpg"]
    },
    slate: {
        name: "Slate River Falls",
        location: "Skanee, Michigan",
        coordinates: { lat: 46.9256, lng: -88.1383 },
        state: "michigan",
        height: "20ft",
        description: "Falls on Slate River with slate rock formations.",
        directions: "Slate River Road from Skanee.",
        bestTime: "Spring through fall",
        features: ["Slate rock", "Slate River", "Geology"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail hike",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trail.",
        images: ["slateriverfalls2.jpg"]
    },
    powerhouse: {
        name: "Powerhouse Falls",
        location: "South Range, Michigan",
        coordinates: { lat: 47.0700, lng: -88.6433 },
        state: "michigan",
        height: "25ft",
        description: "Falls near old powerhouse ruins.",
        directions: "Powerhouse Road from South Range.",
        bestTime: "Spring through fall",
        features: ["Historic ruins", "Industrial history", "Unique setting"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail to ruins",
        dogFriendly: true,
        dogInfo: "Dogs allowed, watch around old structures.",
        images: ["powerhousefalls2.jpg"]
    },
    reany: {
        name: "Reany Falls",
        location: "Michigamme, Michigan",
        coordinates: { lat: 46.5369, lng: -88.1086 },
        state: "michigan",
        height: "15ft",
        description: "Falls on Peshekee River.",
        directions: "Peshekee Grade from US-41.",
        bestTime: "Spring through fall",
        features: ["Peshekee River", "Mining history", "Forest"],
        difficulty: "moderate",
        difficultyText: "Moderate - Old road access",
        dogFriendly: true,
        dogInfo: "Dogs allowed on old roads.",
        images: ["vreanycreekfalls1.jpg"]
    },
    // Wisconsin Waterfalls
    bigmanitou: {
        name: "Big Manitou Falls",
        location: "Superior, Wisconsin",
        coordinates: { lat: 46.5283, lng: -92.1205 },
        state: "wisconsin",
        height: "165ft",
        description: "Wisconsin's tallest waterfall and 4th highest east of the Rockies.",
        directions: "Pattison State Park, 13 miles south of Superior.",
        bestTime: "Spring for flow, fall for colors",
        features: ["Tallest in Wisconsin", "Suspension footbridge", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk from parking",
        dogFriendly: true,
        dogInfo: "Dogs allowed on 6-foot leash in park.",
        images: ["vbigmanitoufalls12.jpg"]
    },
    littlemanitou: {
        name: "Little Manitou Falls",
        location: "Superior, Wisconsin",
        coordinates: { lat: 46.5194, lng: -92.1183 },
        state: "wisconsin",
        height: "31ft",
        description: "Smaller companion to Big Manitou in Pattison State Park.",
        directions: "Pattison State Park, downstream from Big Manitou.",
        bestTime: "Spring through fall",
        features: ["State park", "Forest trail", "Swimming beach nearby"],
        difficulty: "easy",
        difficultyText: "Easy - Short trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash throughout park.",
        images: ["littlemanitou3.jpg"]
    },
    amnicon: {
        name: "Amnicon Falls",
        location: "South Range, Wisconsin",
        coordinates: { lat: 46.6106, lng: -91.8894 },
        state: "wisconsin",
        height: "30ft",
        description: "Series of waterfalls and rapids in Amnicon Falls State Park.",
        directions: "US-2 east of Superior, follow signs to state park.",
        bestTime: "Spring and early summer",
        features: ["Multiple falls", "Covered bridge", "State park"],
        difficulty: "easy",
        difficultyText: "Easy - Developed paths",
        dogFriendly: true,
        dogInfo: "Dogs welcome on leash. Multiple viewing areas.",
        images: ["vamniconupper1.jpg"]
    },
    copper: {
        name: "Copper Falls",
        location: "Mellen, Wisconsin",
        coordinates: { lat: 46.3669, lng: -90.6481 },
        state: "wisconsin",
        height: "40ft",
        description: "Beautiful Wisconsin falls in Copper Falls State Park.",
        directions: "Copper Falls State Park near Mellen, WI.",
        bestTime: "Spring through fall",
        features: ["State park", "Lava flows", "Brownstone Falls nearby"],
        difficulty: "easy",
        difficultyText: "Easy - Developed trails",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash in state park.",
        images: ["vcopperfalls1.jpg"]
    },
    brownstone: {
        name: "Brownstone Falls",
        location: "Mellen, Wisconsin",
        coordinates: { lat: 46.3658, lng: -90.6472 },
        state: "wisconsin",
        height: "30ft",
        description: "Companion falls to Copper Falls in same state park.",
        directions: "Copper Falls State Park near Mellen, WI.",
        bestTime: "Spring through fall",
        features: ["Tyler Forks", "State park", "Near Copper Falls"],
        difficulty: "easy",
        difficultyText: "Easy - Park trails",
        dogFriendly: true,
        dogInfo: "Dogs welcome on park trails.",
        images: ["vbrownstonefalls1.jpg"]
    },
    potato: {
        name: "Potato River Falls",
        location: "Gurney, Wisconsin",
        coordinates: { lat: 46.4850, lng: -90.2236 },
        state: "wisconsin",
        height: "90ft total",
        description: "Series of cascades on Potato River.",
        directions: "Highway 169 south of Gurney, marked parking area.",
        bestTime: "Spring for high water",
        features: ["Upper and lower falls", "Gorge views", "Observation deck"],
        difficulty: "moderate",
        difficultyText: "Moderate - Stairs to lower falls",
        dogFriendly: true,
        dogInfo: "Dogs allowed. Stairs can be challenging for some dogs.",
        images: ["potatolowerfalls3.jpg"]
    },
    saxon: {
        name: "Saxon Falls",
        location: "Saxon, Wisconsin",
        coordinates: { lat: 46.5039, lng: -90.4089 },
        state: "wisconsin",
        height: "84ft",
        description: "Impressive cascade on Montreal River.",
        directions: "US-2 at Saxon, follow signs to falls.",
        bestTime: "Any season due to dam control",
        features: ["Dam controlled", "Year-round flow", "Hydroelectric"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk",
        dogFriendly: true,
        dogInfo: "Dogs allowed in viewing areas.",
        images: ["saxonfalls12.jpg"]
    },
    superior: {
        name: "Superior Falls",
        location: "Saxon, Wisconsin",
        coordinates: { lat: 46.4894, lng: -90.4244 },
        state: "wisconsin",
        height: "90ft",
        description: "Powerful falls on Montreal River.",
        directions: "US-2 west of Saxon, marked parking.",
        bestTime: "Spring for maximum flow",
        features: ["Interstate falls", "Montreal River", "Border location"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail to views",
        dogFriendly: true,
        dogInfo: "Dogs allowed on trails.",
        images: ["superiorfalls3.jpg"]
    },
    longslide: {
        name: "Long Slide Falls",
        location: "Pembine, Wisconsin",
        coordinates: { lat: 45.5972, lng: -88.0833 },
        state: "wisconsin",
        height: "50ft",
        description: "Natural water slide popular for swimming.",
        directions: "Twelve Foot Falls Park, Marinette County.",
        bestTime: "Summer for swimming",
        features: ["Natural slide", "Swimming hole", "County park"],
        difficulty: "easy",
        difficultyText: "Easy - Park access",
        dogFriendly: true,
        dogInfo: "Dogs love swimming here in designated areas.",
        images: ["vlongslidefalls2.jpg"]
    },
    daves: {
        name: "Dave's Falls",
        location: "Amberg, Wisconsin",
        coordinates: { lat: 45.4942, lng: -87.9961 },
        state: "wisconsin",
        height: "35ft",
        description: "Popular county park with swimming and picnic facilities.",
        directions: "Dave's Falls County Park on Pike River.",
        bestTime: "Summer for recreation",
        features: ["Swimming", "County park", "Picnic facilities"],
        difficulty: "easy",
        difficultyText: "Easy - Developed park",
        dogFriendly: true,
        dogInfo: "Dogs welcome. Great swimming spot for dogs.",
        images: ["davesfalls5.jpg"]
    },
    wren: {
        name: "Wren Falls",
        location: "Spread Eagle, Wisconsin",
        coordinates: { lat: 45.8067, lng: -88.1406 },
        state: "wisconsin",
        height: "15ft",
        description: "Small scenic falls with good fishing.",
        directions: "Near Spread Eagle on Pine River.",
        bestTime: "Spring through fall",
        features: ["Fishing", "Less crowded", "Pine River"],
        difficulty: "easy",
        difficultyText: "Easy - Short walk",
        dogFriendly: true,
        dogInfo: "Dogs allowed. Good spot for water-loving dogs.",
        images: ["wrenfalls2.jpg"]
    },
    interstate: {
        name: "Interstate Falls",
        location: "Hurley, Wisconsin",
        coordinates: { lat: 46.4611, lng: -90.1936 },
        state: "wisconsin",
        height: "20ft",
        description: "Falls on Montreal River at Michigan-Wisconsin border.",
        directions: "US-2 between Ironwood and Hurley.",
        bestTime: "Spring through fall",
        features: ["Border location", "Mining history", "Montreal River"],
        difficulty: "easy",
        difficultyText: "Easy - Near highway",
        dogFriendly: true,
        dogInfo: "Dogs allowed in park areas.",
        images: ["interstatefalls3.jpg"]
    },
    morgan: {
        name: "Morgan Falls",
        location: "Mellen, Wisconsin",
        coordinates: { lat: 46.3031, lng: -90.7256 },
        state: "wisconsin",
        height: "70ft",
        description: "Tallest waterfall in Chequamegon National Forest.",
        directions: "Forest roads from Mellen, can be rough.",
        bestTime: "Spring after snowmelt",
        features: ["National Forest", "Remote", "Tall drop"],
        difficulty: "hard",
        difficultyText: "Challenging - Remote location",
        dogFriendly: true,
        dogInfo: "Dogs allowed but challenging access.",
        images: ["vmorganfalls1.jpg"]
    },
    foster: {
        name: "Foster Falls",
        location: "Mountain, Wisconsin",
        coordinates: { lat: 45.1833, lng: -88.4667 },
        state: "wisconsin",
        height: "25ft",
        description: "Scenic falls on Popple River.",
        directions: "Off Highway 32 near Mountain.",
        bestTime: "Spring through fall",
        features: ["Popple River", "Fishing", "Forest"],
        difficulty: "moderate",
        difficultyText: "Moderate - Trail required",
        dogFriendly: true,
        dogInfo: "Dogs welcome on trails.",
        images: ["vfosterfalls1.jpg"]
    },
    willow: {
        name: "Willow Falls",
        location: "Hudson, Wisconsin",
        coordinates: { lat: 44.9719, lng: -92.6267 },
        state: "wisconsin",
        height: "100ft wide",
        description: "Wisconsin's widest waterfall.",
        directions: "Willow River State Park near Hudson.",
        bestTime: "Spring through fall",
        features: ["Widest in Wisconsin", "State park", "Swimming"],
        difficulty: "moderate",
        difficultyText: "Moderate - Steep trail",
        dogFriendly: true,
        dogInfo: "Dogs allowed on leash. Steep trail to falls.",
        images: ["willowfalls2.jpg"]
    },
    cascade: {
        name: "Cascade Falls",
        location: "Osceola, Wisconsin",
        coordinates: { lat: 45.3194, lng: -92.7039 },
        state: "wisconsin",
        height: "25ft",
        description: "Downtown waterfall with historic mill.",
        directions: "Downtown Osceola, Cascade Street.",
        bestTime: "Year-round",
        features: ["Urban falls", "Historic mill", "Downtown"],
        difficulty: "easy",
        difficultyText: "Easy - Downtown location",
        dogFriendly: true,
        dogInfo: "Dogs welcome in downtown area.",
        images: ["cascadefallsosceola4.jpg"]
    },
    bigsmokey: {
        name: "Big Smokey Falls",
        location: "Loretta, Wisconsin",
        coordinates: { lat: 45.7833, lng: -91.0667 },
        state: "wisconsin",
        height: "30ft",
        description: "Remote waterfall on Wolf River.",
        directions: "Forest roads from Loretta.",
        bestTime: "Spring through fall",
        features: ["Wolf River", "Whitewater", "Remote"],
        difficulty: "hard",
        difficultyText: "Challenging - Remote location",
        dogFriendly: true,
        dogInfo: "Dogs allowed but remote access.",
        images: ["bigsmokeyfalls1.jpg"]
    },
    high: {
        name: "High Falls (Peshtigo)",
        location: "Crivitz, Wisconsin",
        coordinates: { lat: 45.4500, lng: -88.2000 },
        state: "wisconsin",
        height: "50ft",
        description: "Tallest falls on Peshtigo River.",
        directions: "High Falls Park from Crivitz.",
        bestTime: "Year-round",
        features: ["Dam", "Park facilities", "Peshtigo River"],
        difficulty: "easy",
        difficultyText: "Easy - Park setting",
        dogFriendly: true,
        dogInfo: "Dogs welcome in park on leash.",
        images: ["highfalls3.jpg"]
    }
};

// Export for use in HTML file
if (typeof module !== 'undefined' && module.exports) {
    module.exports = waterfallData;
}